name: CI

on:
  push:   #Run on all push
    branches: [ "main" ]
  pull_request:   # And all PRs

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest

      - name: Run unit tests
        run: pytest -q
